name: common_core
description: "A new Flutter project."

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1
publish_to: none  # 表示这是本地包

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.19.0    #日期格式化
  basic_utils: ^5.7.0     #https://pub.dev/packages/basic_utils
  common_utils: ^2.1.0    #https://pub-web.flutter-io.cn/packages/common_utils
  flustars: ^2.0.1
  sprintf: ^7.0.0    #https://pub-web.flutter-io.cn/packages/sprintf
  event_bus: ^2.0.0 #https://pub-web.flutter-io.cn/packages/event_bus/example
  rxdart: ^0.27.7 #https://pub-web.flutter-io.cn/packages/rxdart/example
  dio: ^5.2.1+1
  talker_dio_logger: ^4.6.4
  chucker_flutter: 1.8.3  #https://pub-web.flutter-io.cn/packages/chucker_flutter
  get: ^4.6.5   #https://pub-web.flutter-io.cn/packages/get
  logger: ^2.0.2+1   # https://pub-web.flutter-io.cn/packages/logger

  cached_network_image: ^3.3.1    #https://pub-web.flutter-io.cn/packages/cached_network_image
  flutter_smart_dialog: ^4.9.4  #https://juejin.cn/post/7026150456673959943  #使用例子 https://xdd666t.github.io/flutter_use/web/index.html#/smartDialog?dialogType=CustomDialogLocation
  package_info_plus: ^8.1.3  #https://pub-web.flutter-io.cn/packages/package_info_plus
  shared_preferences: ^2.2.2    #https://pub-web.flutter-io.cn/packages/shared_preferences/install
  #webview_flutter: ^4.2.2
  card_swiper: ^3.0.1   #https://pub-web.flutter-io.cn/packages/card_swiper/install
  flutter_constraintlayout: ^1.7.0-stable   #https://github.com/hackware1993/Flutter_ConstraintLayout/blob/master/README_CN.md
  #  easy_refresh: ^3.3.2+1 #https://pub.dev/packages/easy_refresh/example
  pull_to_refresh: ^2.0.0  #https://github.com/peng8350/flutter_pulltorefresh
  permission_handler: ^11.0.1 #https://pub-web.flutter-io.cn/packages/permission_handler/example
  device_info_plus: ^11.2.1   #https://pub-web.flutter-io.cn/packages/device_info_plus/example
  image_picker: ^1.0.4    #https://pub-web.flutter-io.cn/packages/image_picker
  video_player: ^2.7.2
  path_provider: ^2.1.1   #https://pub-web.flutter-io.cn/packages/path_provider
  flutter_native_splash: ^2.4.0   #https://pub-web.flutter-io.cn/packages/flutter_native_splash
  #  install_plugin: ^2.1.0
  url_launcher: ^6.2.1  #https://pub-web.flutter-io.cn/packages/url_launcher/install
  photo_view: ^0.15.0  #https://pub-web.flutter-io.cn/packages/photo_view
  scrollview_observer: ^1.24.0 #https://pub.dev/packages/scrollview_observer
  #  flutter_statusbarcolor_ns: ^0.5.0  #https://pub.dev/packages/flutter_statusbarcolor_ns/example
  #  animate_do: ^3.3.4 #https://pub-web.flutter-io.cn/packages/animate_do
  flutter_animate: ^4.5.0 #https://pub-web.flutter-io.cn/packages/flutter_animate
  #https://github.com/OctMon/flutter_easy


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: DINPRO
      fonts:
        - asset: assets/fonts/dinpro.ttf
        - asset: assets/fonts/dinpro_bold.ttf
        - asset: assets/fonts/dinpro_medium.ttf

#https://pub-web.flutter-io.cn/packages/flutter_native_splash
flutter_native_splash:
  color: "#ffffff"
  image: assets/ic_logo.jpeg
  android_gravity: center # 设置图片居中
  ios_content_mode: center # 在iOS上也确保图片居中

# https://pub-web.flutter-io.cn/packages/flutter_launcher_icons
#  执行命令
#  flutter pub get
#  flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/ic_logo.jpeg"
  #  image_path_android: "icons/ic_launcher.png"
  #  image_path_ios: "icons/ios_marketing.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.xh.common_core.common_core
    iosBundleIdentifier: com.xh.commoncore.commonCore

