name: common_core
description: "A new Flutter project."


version: 1.0.0+1
publish_to: none  # 表示这是本地包


environment:
  sdk: ^3.7.0-209.1.beta


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0    #日期格式化
  #网络
  dio: ^5.8.0+1                  #https://pub-web.flutter-io.cn/packages/dio
  talker_dio_logger: ^4.6.11     #https://pub-web.flutter-io.cn/packages/talker_dio_logger
  chucker_flutter: 1.8.3         #https://pub-web.flutter-io.cn/packages/chucker_flutter
  logger: ^2.5.0                 #https://pub-web.flutter-io.cn/packages/logger
  get: ^4.6.5                    #https://pub-web.flutter-io.cn/packages/get
  #必备
  flutter_native_splash: ^2.4.4   #https://pub-web.flutter-io.cn/packages/flutter_native_splash
  flutter_launcher_icons: ^0.14.3 #https://pub-web.flutter-io.cn/packages/flutter_launcher_icons
  cached_network_image: ^3.4.1    #https://pub-web.flutter-io.cn/packages/cached_network_image
  flutter_smart_dialog: ^4.9.8+6  #https://juejin.cn/post/7026150456673959943  #使用例子 https://xdd666t.github.io/flutter_use/web/index.html#/smartDialog?dialogType=CustomDialogLocation
  package_info_plus: ^8.2.1       #https://pub-web.flutter-io.cn/packages/package_info_plus
  shared_preferences: ^2.5.2      #https://pub-web.flutter-io.cn/packages/shared_preferences/install
  webview_flutter: ^4.10.0        #https://pub.dev/packages/webview_flutter
  permission_handler: ^11.3.1     #https://pub-web.flutter-io.cn/packages/permission_handler/example
  device_info_plus: ^11.3.0       #https://pub-web.flutter-io.cn/packages/device_info_plus/example
  #组件
  pull_to_refresh: ^2.0.0         #https://github.com/peng8350/flutter_pulltorefresh
  easy_refresh: ^3.4.0            #https://pub.dev/packages/easy_refresh/example
  path_provider: ^2.1.5           #https://pub-web.flutter-io.cn/packages/path_provider
  image_picker: ^1.1.2            #https://pub-web.flutter-io.cn/packages/image_picker
  url_launcher: ^6.3.1            #https://pub-web.flutter-io.cn/packages/url_launcher/install
  animate_do: ^4.0.0              #https://pub-web.flutter-io.cn/packages/animate_do
  flutter_animate: ^4.5.2         #https://pub-web.flutter-io.cn/packages/flutter_animate
  flutter_constraintlayout: ^1.7.0-stable #https://github.com/hackware1993/Flutter_ConstraintLayout/blob/master/README_CN.md
  card_swiper: ^3.0.1             #https://pub-web.flutter-io.cn/packages/card_swiper/install
  extended_sliver: 2.1.3          #https://pub-web.flutter-io.cn/packages/extended_sliver
  photo_view: ^0.15.0             #https://pub-web.flutter-io.cn/packages/photo_view
  scrollview_observer: ^1.25.1    #https://pub.dev/packages/scrollview_observer
  video_player: ^2.7.2            #https://pub.dev/packages/video_player
  #install_plugin: ^2.1.0
  #flutter_statusbarcolor_ns: ^0.6.0  #https://pub.dev/packages/flutter_statusbarcolor_ns/example
  #https://github.com/OctMon/flutter_easy
  #工具
  basic_utils: ^5.7.0           #https://pub.dev/packages/basic_utils
  common_utils: ^2.1.0          #https://pub-web.flutter-io.cn/packages/common_utils
  flustars: ^2.0.1              #https://pub-web.flutter-io.cn/packages/flustars
  sprintf: ^7.0.0               #https://pub-web.flutter-io.cn/packages/sprintf
  event_bus: ^2.0.0             #https://pub-web.flutter-io.cn/packages/event_bus/example
  rxdart: ^0.27.7               #https://pub-web.flutter-io.cn/packages/rxdart/example


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: DINPRO
      fonts:
        - asset: assets/fonts/dinpro.ttf
        - asset: assets/fonts/dinpro_bold.ttf
        - asset: assets/fonts/dinpro_medium.ttf



  module:
    androidX: true
    androidPackage: com.xh.common_core.common_core
    iosBundleIdentifier: com.xh.commoncore.commonCore

