name: flutter_commonlib
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.18.1     #日期格式化
  cupertino_icons: ^1.0.6
  common_utils: ^2.1.0    #https://pub-web.flutter-io.cn/packages/common_utils
  flustars: ^2.0.1
  sprintf: ^7.0.0    #https://pub-web.flutter-io.cn/packages/sprintf
  event_bus: ^2.0.0 #https://pub-web.flutter-io.cn/packages/event_bus/example
  rxdart: ^0.27.7 #https://pub-web.flutter-io.cn/packages/rxdart/example
  dio: ^5.2.1+1
  get: ^4.6.5   #https://pub-web.flutter-io.cn/packages/get
  logger: ^2.0.2+1   # https://pub-web.flutter-io.cn/packages/logger
  flutterlifecyclehooks : ^3.0.2
  cached_network_image: ^3.2.3    #https://pub-web.flutter-io.cn/packages/cached_network_image
  flutter_smart_dialog: ^4.9.4  #https://juejin.cn/post/7026150456673959943  #使用例子 https://xdd666t.github.io/flutter_use/web/index.html#/smartDialog?dialogType=CustomDialogLocation
  # platform_device_id: ^1.0.1
  package_info_plus: ^4.2.0   #https://pub-web.flutter-io.cn/packages/package_info_plus
  #webview_flutter: ^4.2.2
  card_swiper: ^3.0.1   #https://pub-web.flutter-io.cn/packages/card_swiper/install
  flutter_constraintlayout: ^1.7.0-stable   #https://github.com/hackware1993/Flutter_ConstraintLayout/blob/master/README_CN.md
  #  easy_refresh: ^3.3.2+1 #https://pub.dev/packages/easy_refresh/example
  pull_to_refresh: ^2.0.0  #https://github.com/peng8350/flutter_pulltorefresh
  permission_handler: ^11.0.1 #https://pub-web.flutter-io.cn/packages/permission_handler/example
  device_info_plus: ^9.1.0   #https://pub-web.flutter-io.cn/packages/device_info_plus/example
  flutter_statusbarcolor_ns: ^0.5.0  #https://pub.dev/packages/flutter_statusbarcolor_ns/example
  #  camera: ^0.10.5+3   #https://pub.dev/packages/camera/example
  image_picker: ^1.0.4    #https://pub-web.flutter-io.cn/packages/image_picker
  video_player: ^2.7.2
  path_provider: ^2.1.1   #https://pub-web.flutter-io.cn/packages/path_provider
  flutter_native_splash: ^2.3.4   #https://pub-web.flutter-io.cn/packages/flutter_native_splash
  install_plugin: ^2.1.0
  url_launcher: ^6.2.1  #https://pub-web.flutter-io.cn/packages/url_launcher/install
  flutter_local_notifications: ^16.1.0 #https://pub-web.flutter-io.cn/packages/flutter_local_notifications/install
  photo_view: ^0.14.0  #https://pub-web.flutter-io.cn/packages/photo_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: DINPRO
      fonts:
        - asset: assets/fonts/dinpro.ttf
        - asset: assets/fonts/dinpro_bold.ttf
        - asset: assets/fonts/dinpro_medium.ttf


flutter_native_splash:
  color: "#ffffff"
  image: assets/ic_logo.jpeg
  color_dark: "#ffffff"
  android_12:
    image: assets/ic_logo.jpeg
    color: "#ffffff"
    icon_background_color: "#eeeeee"
  fullscreen: true